version: '3.8'

services:
  stackup-assistant:
    build: .
    volumes:
      - .:/app
    ports:
      - "60675:60675"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    command: ["python", "main.py"]
    