version: '3.8'

services:
  stackup-assistant:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # This exposes the container's port 5000 to the host's port 5000
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    command: ["taipy", "run", "main.py", "--use-reloader"]
